spring:

  datasource:
    url: ENC(FnnhWrmY3pA1rno21vU8tB2HfUwvd5PyptYzB3+WkMrW2gKKaPTPkRclaLzwsxANnAWOphWY9dgElxqtOafNX2+exiK53GAPJSD9Ow7D/9ZEAk3QORu3mZ4ScrOSrUcU)
    username: ENC(KY+dZQ4q1YBP4MhUxz2cZL+8jHcp6Up+spmdc91XcYo=)
    password: ENC(LPzOI74cooQPPNGDuvn8P9EW+9/p1XmeuD+EslyH3+A=)
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8082

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: info

token:
  secret: sloth-backend
  access-token-expiration-time: 99999999999
  refresh-token-expiration-time: 99999999999