#이 파일은 깃허브에 올라가면 안됨
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 151935241850-4jk4v4dj9bihjm5fpj3dva28oke08l6n.apps.googleusercontent.com
            client-secret: ENC(EYoEIYnOF4GK9e1EIH8wyt4CrQ2qud5qXA/jEuhl09ORFIj6zCj5239k0fiba+IL)
            # scope에 openid는 빼고 등록. 그래야 OpenId Provider 서비스(구글)와 그렇지 않은 서비스(네이버/카카오 등)로 나눠서 Oauth2Service를 안만들어도됨
            scope: profile,email
          naver:
            client-id: HAu37bfw0CtS6FNA8Afp
            client-secret: ENC(5uaNLq1gpFbIiiHQw+E6ZHm9uXIPnwxbCXZXSaCRaRs=)
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver

        # 네이버는 스프링 시큐리티에서 공식 지원하지 않기 때문에 CommonOauth2Provider에서 해주던 값들도 전부 수동 입력해줘야한다.
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # 기준이 되는 user_name의 이름을 네이버에서는 response로 해야 한다.
            # 이유는 네이버 회원 조회 시 반환되는 JSON 형태 때문이다.
            user-name-attribute: response
