spring:

  session:
    jdbc:
      initialize-schema: always

  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql : true
        default_batch_fetch_size: 1000
        use_sql_comments: true
        open-in-view: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    enabled: true
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  profiles:
    include: oauth

  messages:
    basename: messages,errors

  # java mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(cgeXjHOUAmf2LXjWc9nPBORZlnLANNcu7Xe9aPqgNBt/XsumSTpuuyE5gKIldvqt)
    password: ENC(qIezXA3iP6vPbAezSE7Ac2HmWRedxtJ8HEfAe7RxooQnI3hT/O+qlSsGAoWKRoMG)
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  cloud:
    gcp:
      storage:
        credentials:
          location: /home/ec2-user/nanagong-storage-e6525987fc74.json

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: info
    org.springframework.security: info
  config: classpath:logback-spring.xml

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: never

restemplate:
  readTimeout: 50000
  connectTimeout: 30000
  maxConnTotal: 100
  maxConnPerRoute: 5

jasypt:
  encryptor:
    bean: encryptorBean

token:
  secret: sloth-backend
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1210500000 # 2주

nanagong:
  enc:
    password: ${ENC_PASSWORD}


management:
  endpoints:
    web:
      exposure:
        include: caches,beans,env,health,heapdump,info,metrics,threaddump
  endpoint:
    health:
      show-details: always


cloud:
  aws:
    credentials:
      access-key: ENC(XHZ23sY+IHsITc+pQym2tCrULlV75a/XGHEk4cyBFAB1OHQZGlyLZWE/XSo5bp7z)
      secret-key: ENC(H9f2a1oBaE4dM2c9ftsSCo6vM9xWlCE/nXqJNAnw6odsepl1fQvpkCgoJ2IbZvMxhI5B2XB9pRechMplc1dNEQ==)
    s3:
      bucket: ENC(Tebv8rycP1iyS5ZNEl+yaJBRIozrHTjfMiegdv40bmk=)
    region:
      static: ap-northeast-2
    stack:
      auto: false

google-cloud:
  project: nanagong-storage
  profile-storage-url: https://storage.googleapis.com/nanagong-profile/
  profile-bucket-name: nanagong-profile