server:
  port: 5000

spring:
  datasource:
    hikari.maximum-pool-size: 4
    username: ENC(YR5xEpjJNYqdPu1GyFdMpMCjtsvnDqn1/V8XevqpjK4=)
    password: ENC(FUiwj17xVnSL/Vf1IFq0UOy3iJBpgX+neQa2/Fo1Pac=)
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(HSma0WziZjAMPv4CIoMIfKSUAffCfcA9PZ2Zlt8BBy1yk63epRdrUKEz5EOQhW1TOuEOtXisF5eyXR8Lm+9qBpiCE/Fw8b2IZ9bKZ6mCO7+K2G/ilIqyns1rBDKm0sCwfhefSj8MYQk6szve/Seq0YFKhYjWdZdVORbQub6u3VXS2EC9ZGp5w7/1UCEJp/dO)
